// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCRQIhsGS3xrGeopcSPW70zal2yNRIQAJc',
    appId: '1:147590035506:web:15f2ca0c967df384a8e42b',
    messagingSenderId: '147590035506',
    projectId: 'jhatfat',
    authDomain: 'jhatfat.firebaseapp.com',
    databaseURL: 'https://jhatfat-default-rtdb.firebaseio.com',
    storageBucket: 'jhatfat.appspot.com',
    measurementId: 'G-35Q59JY3SN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCTsuo3QSNdQmKWM3KUGQpYo-BrSWvNRjQ',
    appId: '1:147590035506:android:3fc8ad80c32e0fbea8e42b',
    messagingSenderId: '147590035506',
    projectId: 'jhatfat',
    databaseURL: 'https://jhatfat-default-rtdb.firebaseio.com',
    storageBucket: 'jhatfat.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD0VeDukc0Mbpzn48YPH1EkRMmc1rFziWw',
    appId: '1:147590035506:ios:d7882d6e8843f964a8e42b',
    messagingSenderId: '147590035506',
    projectId: 'jhatfat',
    databaseURL: 'https://jhatfat-default-rtdb.firebaseio.com',
    storageBucket: 'jhatfat.appspot.com',
    androidClientId: '147590035506-2slegfg152au1mrojkk9p6ls79g3kih8.apps.googleusercontent.com',
    iosClientId: '147590035506-2geii1dnk3m8dmphdecg0i7ch5ujk3a1.apps.googleusercontent.com',
    iosBundleId: 'com.jhatfat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD0VeDukc0Mbpzn48YPH1EkRMmc1rFziWw',
    appId: '1:147590035506:ios:3f8e27d676f6682da8e42b',
    messagingSenderId: '147590035506',
    projectId: 'jhatfat',
    databaseURL: 'https://jhatfat-default-rtdb.firebaseio.com',
    storageBucket: 'jhatfat.appspot.com',
    androidClientId: '147590035506-2slegfg152au1mrojkk9p6ls79g3kih8.apps.googleusercontent.com',
    iosClientId: '147590035506-psglmtspgbfhmombo8sf5m5o2r1nktul.apps.googleusercontent.com',
    iosBundleId: 'com.jhatfatflutterNew',
  );
}
