var baseUrl = "https://jhatfat.com/api/";
var imageBaseUrl = "https://jhatfat.com/";

var adminsettings = baseUrl + "adminsettings";
var addwallet = baseUrl + "addwallet";
var checksubs = baseUrl + "checksubs";
var subsstore = baseUrl + "subsstore";
var deleteaccount = baseUrl + "deleteaccount";
var ordercharges = baseUrl + "ordercharges";
var servicecharges = baseUrl + "servicecharges";
var top_msg_banner = baseUrl + "top_message_banner";
var closed_banner = baseUrl + "closed_banner";
var pickdropbanner = baseUrl + "parbanner";
var subsbanner = baseUrl + "subsbanner";
var bigbanner = baseUrl + "bigbanner";
var registerApi = baseUrl + "user_register";
var verifyPhone = baseUrl + "verify_phone";
var userRegistration = baseUrl + "checkuser";
var parcel_check_location = baseUrl + "parcel_check_location";
var userProfile = baseUrl + "myprofile";
var forgotPassword = baseUrl + "forgot_password";
var forgotPasswordVerify = baseUrl + "verify_otp";
var changePassword = baseUrl + "change_password";
var nearByStore = baseUrl + "nearbystore";
var nearbyrest = baseUrl + "nearbyrest";
var bannerUrl = baseUrl + "adminbanner";
var categoryList = baseUrl + "appcategory";
var subCategoryList = baseUrl + "appsubcategory";
var productListWithVarient = baseUrl + "appproduct";
var vendorUrl = baseUrl + "vendorcategory";
var newvendorUrl = baseUrl + "vendorcategorylist";
var subscriptionList = baseUrl + "planlist";
var subscribe = baseUrl + "subscribe";
var addToCart = baseUrl + "order";
var idupload = baseUrl + "upload_id";
var checkid = baseUrl + "check_id";
var timeSlots = baseUrl + "timeslot";
var applyCoupon = baseUrl + "apply_coupon";
var couponList = baseUrl + "coupon_list";
var checkOut = baseUrl + "checkout";
var addAddress = baseUrl + "add_address";
var showAddress = baseUrl + "show_address";
var area_city_charges = baseUrl + "area_city_charges";
var selectAddress = baseUrl + "select_address";
var removeAddress = baseUrl + "remove_address";
var editAddress = baseUrl + "edit_address";
var vendorBanner = baseUrl + "vendorbanner";
var Search_key = baseUrl + "search";
var restSearch_key = baseUrl + "searchrest";
var RestSearch_key = baseUrl + "restsearch";
var storesearch = baseUrl + "storesearch";
var orderdetails = baseUrl + "orderdetails";
var parceldetails = baseUrl + "parceldetails";
var onGoingOrdersUrl = baseUrl + "ongoingorders";
var completeOrders = baseUrl + "completed_orders1";
var cancelOrders = baseUrl + "cancelorderhistory";
var cityList = baseUrl + "city";
var areaLists = baseUrl + "area";
var address_selection = baseUrl + "address_selection";
var cancelReasonList = baseUrl + "showcomplain";
var cancelOrderApi = baseUrl + "cancel_order";
var rewardvalues = baseUrl + "rewardvalues";
var search_keyword = baseUrl + "search_keyword";
var after_order_reward_msg = baseUrl + "after_order_reward_msg";
var rewardhistory = baseUrl + "rewardhistory";
var redeem = baseUrl + "redeem";
var showWalletAmount = baseUrl + "showcredit";
var creditHistroy = baseUrl + "credit_history";
var termcondition = baseUrl + "termcondition";
var aboutus = baseUrl + "aboutus";
var support = baseUrl + "support";
var reffermessage = baseUrl + "reffermessage";
var paymentvia = baseUrl + "paymentvia"; //vendor_id
var currencyuri = baseUrl + "currency"; //vendor_id
var notificationlist = baseUrl + "notificationlist"; //vendor_id
var dealproductUrl = baseUrl + "dealproduct"; //vendor_id
var notificationby = baseUrl + "notificationby"; //vendor_id
var promocode_regenerate = baseUrl + "promocode_regenerate"; //vendor_id
var country_code = baseUrl + "country_code"; //vendor_id
// resturant model
var resturant_banner = baseUrl+"resturant_banner";
var homecategoryss = baseUrl+"homecategory";
var popular_item = baseUrl+"popular_item";
var returant_order = baseUrl+"returant_order";
var orderplaced = baseUrl+"orderplaced";
var order_cancel = baseUrl+"order_cancel";
var resturantsearchingFor = baseUrl+"resturantsearchingFor";
var user_completed_orders = baseUrl+"user_completed_orders";
var user_cancel_order_history = baseUrl+"user_cancel_order_history";
var user_ongoing_order = baseUrl+"user_ongoing_order";

//pharmacy
var pharmacy_banner = baseUrl+"pharmacy_banner";
var pharmacy_homecategory = baseUrl+"pharmacy_homecategory";
var pharmacy_popular_item = baseUrl+"pharmacy_popular_item";
var pharmacy_order = baseUrl+"pharmacy_order";
var pharmacy_orderplaced = baseUrl+"pharmacy_orderplaced";
var pharmacy_order_cancel = baseUrl+"pharmacy_order_cancel";
var pharmacy_user_completed_orders = baseUrl+"pharmacy_user_completed_orders";
var pharmacy_user_cancel_order_history = baseUrl+"pharmacy_user_cancel_order_history";
var pharmacy_user_ongoing_order = baseUrl+"pharmacy_user_ongoing_order";
var after_order_reward_msg_new = baseUrl+"after_order_reward_msg_new";

// parcel
var parcel_banner = baseUrl+"parcel_banner";
var parcel_detail = baseUrl+"parcel_detail";//add to cart
var parcel_detail2 = baseUrl+"parcel_detail";//add to cart
var parcel_charges = baseUrl+"parcel_charges";
var parcel_orderplaced = baseUrl+"parcel_orderplaced";//checkout
var parcel_listcharges = baseUrl+"parcel_listcharges";
var parcel_after_order_reward_msg = baseUrl+"parcel_after_order_reward_msg";
var parcel_user_ongoing_order = baseUrl+"parcel_user_ongoing_order";
var parcel_user_cancel_order = baseUrl+"parcel_user_cancel_order";
var parcel_user_completed_order = baseUrl+"parcel_user_completed_order";

var appname = "jhatfat";
